version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - bot-db:/var/lib/mysql
  discord_bot:
    build: .
    volumes:
      - .:/code
    links:
      - db
volumes:
  bot-db: